- name: /etc/pam.d/system-auth 파일이 존재하는지 확인
  stat:
    path: /etc/pam.d/system-auth
  register: system_auth_stat
  ignore_errors: yes

- name: /etc/pam.d/system-auth 파일에서 비밀번호 복잡성과 enforce_for_root 확인
  shell: cat /etc/pam.d/system-auth
  register: system_auth_content
  when: system_auth_stat.stat.exists
  ignore_errors: yes

- name: pam_pwquality.conf 파일이 존재하는지 확인
  stat:
    path: /etc/security/pwquality.conf
  register: pwquality_conf_stat
  ignore_errors: yes

- name: /etc/security/pwquality.conf 파일에서 minlen 값 확인
  shell: grep -E '^minlen\s*=\s*([8-9]|1[0-9])' /etc/security/pwquality.conf || true
  register: minlen_grep
  when: pwquality_conf_stat.stat.exists
  ignore_errors: yes

- name: /etc/security/pwquality.conf 파일에서 credit 설정 확인 (ucredit, lcredit, dcredit, ocredit)
  shell: grep -E '^(ucredit|lcredit|dcredit|ocredit)\s*=\s*-1' /etc/security/pwquality.conf || true
  register: credit_grep
  when: pwquality_conf_stat.stat.exists
  ignore_errors: yes

- name: 비밀번호 복잡성 조건 평가
  set_fact:
    password_complexity_conditions: >-
      {{
        (minlen_grep.stdout is defined and minlen_grep.stdout != '') and
        (credit_grep.stdout is defined and credit_grep.stdout != '')
      }}
  ignore_errors: yes

- name: system-auth 및 pwquality.conf 조건을 기반으로 scan_results 설정
  set_fact:
    scan_results: "{{ scan_results | combine({
                      'U_02': (system_auth_content.stdout is defined and system_auth_content.stdout != '') and
                              password_complexity_conditions | bool
                    }) }}"
  ignore_errors: yes

