- name: /etc/login.defs 파일이 존재하는지 확인
  stat:
    path: /etc/login.defs
  register: logindefs_stat
  ignore_errors: yes

- name: /etc/login.defs 파일에서 PASS_MAX_DAYS 값 확인 (파일이 존재할 경우)
  shell: grep -E '^PASS_MAX_DAYS' /etc/login.defs | awk '{print $2}' || echo "not_set"
  register: pass_max_days
  when: logindefs_stat.stat.exists
  ignore_errors: yes

- name: PASS_MAX_DAYS 값이 유효한 숫자인지 확인하고 평가
  set_fact:
    pass_max_days_check: >-
      {{
        pass_max_days.stdout is search('^[0-9]+$') and
        (pass_max_days.stdout | int) <= 90
      }}
  ignore_errors: yes

- name: PASS_MAX_DAYS 검사 결과를 기반으로 scan_results 설정
  set_fact:
    scan_results: "{{ scan_results | combine({
                      'U_04': pass_max_days_check | bool
                    }) }}"
  ignore_errors: yes

