- name: Get current PATH environment variable
  shell: echo $PATH
  register: path_env

- name: Check if PATH contains "." at the beginning or middle
  set_fact:
    path_contains_dot: >-
      {{
        path_env.stdout.split(':')[0] == '.' or
        ('.' in path_env.stdout.split(':') and path_env.stdout.split(':')[-1] != '.')
      }}

- name: Set scan_results based on PATH check
  set_fact:
    scan_results: "{{ scan_results | combine({
                      'U_06': not path_contains_dot | bool
                    }) }}"

- name: Display scan_results # 작성 완료 후 삭제 가능
  debug:
    var: scan_results
