- name: Find files and directories with no valid owner or group
  shell: find / -nogroup -o -nouser
  register: invalid_owner_group_files
  ignore_errors: yes

- name: Check if any files or directories have no valid owner or group
  set_fact:
    has_invalid_owner_group: "{{ invalid_owner_group_files.stdout != '' }}"

- name: Set scan_results based on invalid owner or group check
  set_fact:
    scan_results: "{{ scan_results | combine({
                      'U_07': not has_invalid_owner_group | bool
                    }) }}"

- name: Display scan_results # 작성 완료 후 삭제 가능
  debug:
    var: scan_results
