- name: /etc/inetd.conf 파일이 존재하는지 확인
  stat:
    path: /etc/inetd.conf
  register: inetd_stat
  ignore_errors: yes

- name: /etc/xinetd.conf 파일이 존재하는지 확인
  stat:
    path: /etc/xinetd.conf
  register: xinetd_stat
  ignore_errors: yes

- name: /etc/inetd.conf 또는 /etc/xinetd.conf 중 어느 파일을 확인할지 결정
  set_fact:
    inetd_file: "{{ '/etc/inetd.conf' if inetd_stat.stat.exists else '/etc/xinetd.conf' }}"
  when: inetd_stat.stat.exists or xinetd_stat.stat.exists
  ignore_errors: yes

- name: 선택한 inetd 파일의 소유권 및 권한 확인
  stat:
    path: "{{ inetd_file }}"
  register: selected_inetd_stat
  when: inetd_stat.stat.exists or xinetd_stat.stat.exists
  ignore_errors: yes

- name: inetd 또는 xinetd 파일의 소유자가 root이고 권한이 644 이하인지 확인
  set_fact:
    inetd_owner_permission_check: >-
      {{
        selected_inetd_stat.stat.pw_name == 'root' and
        selected_inetd_stat.stat.mode | int(base=8) <= 644
      }}
  when: inetd_stat.stat.exists or xinetd_stat.stat.exists
  ignore_errors: yes

- name: inetd/xinetd 파일의 소유권 및 권한 검사 결과를 기반으로 scan_results 설정
  set_fact:
    scan_results: "{{ scan_results | combine({
                      'U_11': (inetd_owner_permission_check | bool) if (inetd_stat.stat.exists or xinetd_stat.stat.exists) else false
                    }) }}"
  ignore_errors: yes

