- name: 루트 디렉터리에서 모든 전역 쓰기 가능한 파일 찾기
  shell: "find / -xdev -type f -perm -0002 ! -perm -1000 2>/dev/null"
  register: world_writable_files
  ignore_errors: yes

- name: 전역 쓰기 가능한 파일 검사 상태를 true로 초기화
  set_fact:
    world_writable_check: true
  ignore_errors: yes

- name: 전역 쓰기 가능한 파일이 있는지 확인하고 정당성 검토
  set_fact:
    world_writable_check: false
  when: world_writable_files.stdout != ""
  ignore_errors: yes

- name: 전역 쓰기 가능한 파일 검사 결과를 기반으로 scan_results 설정
  set_fact:
    scan_results: "{{ scan_results | combine({
                      'U_16': world_writable_check | bool
                    }) }}"
  ignore_errors: yes

