- name: Check anonymous FTP status in vsftpd.conf
  shell: grep "anonymous_enable" /etc/vsftpd.conf
  register: ftp_anonymous_status
  ignore_errors: yes  # 파일이 없거나 grep이 실패할 경우에도 오류 무시

- name: Evaluate anonymous FTP condition
  set_fact:
    anonymous_ftp_disabled: >-
      {{
        ('anonymous_enable=NO' in ftp_anonymous_status.stdout) or
        ('No such file or directory' in ftp_anonymous_status.stderr)
      }}

- name: Set scan_results based on anonymous FTP condition
  set_fact:
    scan_results: "{{ scan_results | combine({'U_21': anonymous_ftp_disabled}) }}"
