---
- name: 계정 잠금 임계값 확인
  win_shell: |
    $lockoutThreshold = (Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon').LockoutThreshold
    if ($lockoutThreshold -le 5) { Write-Output 'true' }
    else { Write-Output 'false' }
  register: lockout_threshold_check
  ignore_errors: yes

- name: 설정 확인 및 scan_result 업데이트
  set_fact:
    scan_results: "{{ scan_results | combine({ 'W_04': (lockout_threshold_check.stdout == 'true') }) }}"
  ignore_errors: yes
