---
- name: 패스워드 최대 사용기간 확인
  win_shell: |
    $maxPasswordAge = (Get-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters').MaximumPasswordAge
    if ($maxPasswordAge -le 90) { Write-Output 'true' }
    else { Write-Output 'false' }
  register: password_max_age_check

- name: 설정 확인 및 scan_result 업데이트
  set_fact:
    scan_results: "{{ scan_results | combine({ 'W_05': (password_max_age_check.stdout == 'true') }) }}"

