---
- name: ClearTextPassword 설정값 확인
  win_shell: |
    $registryPath = 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters'
    $registryValue = 'ClearTextPassword'
    $value = (Get-ItemProperty -Path $registryPath -Name $registryValue -ErrorAction SilentlyContinue).$registryValue
    if ($value -eq 0) { Write-Output 'true' }
    else { Write-Output 'false' }
  register: clear_text_password_check

- name: 설정 확인 및 scan_result 업데이트
  set_fact:
    scan_results: "{{ scan_results | combine({ 'W_07': (clear_text_password_check.stdout == 'true') }) }}"

