- name: net share 명령어 실행
  win_shell: net share
  register: net_share_output

- name: 일반 공유 디렉터리 필터링
  set_fact:
    general_shares: >
      {{
        net_share_output.stdout_lines
        | select('search', '^(?!C\$|D\$|Admin\$|IPC\$)\w')
        | list
      }}
  ignore_errors: yes

- name: 일반 공유 디렉터리 존재 여부 확인
  set_fact:
    scan_results: "{{ scan_results | combine({ 'W_09': (general_shares | length == 0) }) }}"
  ignore_errors: yes

