---
- name: FTP 서비스 구동 여부 확인
  win_shell: |
    $service = Get-Service -Name "ftpsvc"
    if ($service.Status -eq 'Stopped') { Write-Output 'true' }
    else { Write-Output 'false' }
  register: ftp_service_check
  ignore_errors: yes

- name: FTP 서비스 상태를 scan_result에 설정
  set_fact:
    scan_results: "{{ scan_results | combine({ 'W_13': (ftp_service_check.stdout == 'true') }) }}"
  ignore_errors: yes
