---
- name: FTP 홈디렉터리 경로 설정
  set_fact:
    ftp_home_directory: 'C:\\inetpub\\ftproot'

- name: FTP 홈디렉터리 접근 권한 확인
  win_shell: |
    $acl = Get-Acl -Path "{{ ftp_home_directory }}"
    $everyoneAccess = $acl.Access | Where-Object { $_.IdentityReference -eq 'Everyone' }
    if ($everyoneAccess) { Write-Output 'false' }
    else { Write-Output 'true' }
  register: ftp_directory_permission_check

- name: FTP 디렉터리 권한 상태를 scan_result에 설정
  set_fact:
    scan_results: "{{ scan_results | combine({ 'W_14': (ftp_directory_permission_check.stdout == 'true') }) }}"

