---
- name: Check for latest security patches
  win_updates:
    category_names: ['SecurityUpdates']
    state: searched
  register: update_check

- name: Determine if latest security patches are installed
  set_fact:
    scan_results: "{{ scan_results | combine({'W_19': (update_check.updates | length == 0)}) }}"

