---
- name: Get SAM file ACL
  win_shell: icacls C:\Windows\System32\config\SAM
  register: sam_acl

- name: Check if only Administrator and System have full control
  set_fact:
    scan_results: >-
      {{
        scan_results | combine({
          'W_25': (
            (sam_acl.stdout is search('BUILTIN\\Administrators:\\(F\\)')) and
            (sam_acl.stdout is search('NT AUTHORITY\\SYSTEM:\\(F\\)')) and
            not (sam_acl.stdout is search('^(?!.*(BUILTIN\\Administrators|NT AUTHORITY\\SYSTEM)).*:\\(F\\)'))
          ) | ternary(true, false)
        })
      }}

