---
- name: Check ScreenSaveActive registry value
  win_shell: |
    try {
      $ScreenSaveActive = (Get-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name 'ScreenSaveActive' -ErrorAction Stop).ScreenSaveActive
      Write-Output $ScreenSaveActive
    } catch {
      Write-Output "NotFound"
    }
  register: screensave_active

- name: Check ScreenSaverIsSecure registry value
  win_shell: |
    try {
      $ScreenSaverlSecure = (Get-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name 'ScreenSaverIsSecure' -ErrorAction Stop).ScreenSaverIsSecure
      Write-Output $ScreenSaverlSecure
    } catch {
      Write-Output "NotFound"
    }
  register: screensaver_secure

- name: Check ScreenSaveTimeOut registry value
  win_shell: |
    try {
      $ScreenSaveTimeOut = (Get-ItemProperty -Path 'HKCU:\Control Panel\Desktop' -Name 'ScreenSaveTimeOut' -ErrorAction Stop).ScreenSaveTimeOut
      Write-Output $ScreenSaveTimeOut
    } catch {
      Write-Output "NotFound"
    }
  register: screensave_timeout

- name: Determine if screensaver is active
  set_fact:
    scan_results: "{{ scan_results | combine({
      'W_26': (
        screensave_active.stdout.strip() == '1' and
        screensaver_secure.stdout.strip() == '1' and
        screensave_timeout.stdout.strip() != 'NotFound'
      )
    }) }}"

