---
- name: AutoAdminLogon 레지스트리 값 확인
  win_shell: |
    try {
      $value = (Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoAdminLogon' -ErrorAction Stop).AutoAdminLogon
    } catch {
      $value = "0"
    }
    Write-Output $value
  register: auto_admin_logon
  ignore_errors: yes

- name: AutoAdminLogon이 존재하지 않거나 0인지 확인
  set_fact:
    scan_results: "{{ scan_results | combine({'W_31': (auto_admin_logon.stdout.strip() == '0')}) }}"
  ignore_errors: yes

