---
- name: Ping and check OS
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ping Linux hosts
      ping:
      register: linux_ping_result
      when: ansible_facts['os_family'] != 'Windows'
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Ping Windows hosts
      win_ping:
      register: windows_ping_result
      when: ansible_facts['os_family'] == 'Windows'
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Set OS fact for Linux hosts
      set_fact:
        os_family: "{{ ansible_facts['os_family'] }}"
      when: linux_ping_result.ping is defined

    - name: Set OS fact for Windows hosts
      set_fact:
        os_family: "{{ ansible_facts['os_family'] }}"
      when: windows_ping_result.ping is defined

    - name: Print connection status and OS for Linux
      debug:
        msg: "{{ inventory_hostname }} | {{ 'Connected' if linux_ping_result.ping is defined else 'Disconnected' }} | {{ 'OS: ' ~ os_family if linux_ping_result.ping is defined else 'Ping failed' }}"
      when: ansible_facts['os_family'] != 'Windows'
      ignore_errors: yes

    - name: Print connection status and OS for Windows
      debug:
        msg: "{{ inventory_hostname }} | {{ 'Connected' if windows_ping_result.ping is defined else 'Disconnected' }} | {{ 'OS: ' ~ os_family if windows_ping_result.ping is defined else 'Ping failed' }}"
      when: ansible_facts['os_family'] == 'Windows'
      ignore_errors: yes

